name: rl-sm-vr
channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.10.12 
  - pip
  - pandas
  - openpyxl 
  - plotly
  - jupyter
     
  - pip:
    - ptitprince
    - matplotlib==3.10.0
    - seaborn==0.13.2 